initial draft of CMR UAT integration for insar_tops_burst
ASFHyP3/hyp3-isce2 pull request #70
Opened 2023-05-26 00:18 UTC by asjohnston-asf

2023-05-26 00:44 UTC, asjohnston-asf commented
This is working except for one bug: `make_parameter_file()` assumes the scene name and the SAFE name are the same, so it crashes when attempting to find `{reference_scene}.SAFE/`

```
Traceback (most recent call last):
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/bin/insar_tops_burst", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/asjohnston/src/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 349, in main
    make_parameter_file(
  File "/home/asjohnston/src/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 156, in make_parameter_file
    ref_annotation = [file for file in os.listdir(ref_annotation_path) if os.path.isfile(ref_annotation_path + file)][0]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'S1_249434_IW1_20230523T170733_VV_8850-BURST.SAFE/annotation/'
```

2023-05-31 17:52 UTC, jtherrmann commented
Moved remaining TODOs to https://github.com/ASFHyP3/hyp3-isce2/issues/74

2023-05-31 18:14 UTC, jtherrmann requested changes

2023-05-31 18:14 UTC, jtherrmann commented on CHANGELOG.md
> +* `insar_tops_burst` workflow now takes the burst product names rather than the slc product names
```suggestion
* `insar_tops_burst` workflow now takes the burst product names rather than the SLC product names.
```

2023-05-31 18:14 UTC, jtherrmann commented on src/hyp3_isce2/burst.py
>      NOTE: Will need to be updated when the interface changes.
```suggestion
```

2023-05-31 18:14 UTC, jtherrmann commented on src/hyp3_isce2/insar_tops_burst.py
> +    baseline_perp = topsProc_xml.find(f'.//IW-{reference_scene[12]}_Bperp_at_midrange_for_first_common_burst').text
Let's make a helper function (e.g. `get_swath_number(reference_scene: str) -> int`) and call it everywhere that `reference_scene[12]` is used (I've seen two places so far).

2023-05-31 18:14 UTC, jtherrmann commented on src/hyp3_isce2/insar_tops_burst.py
> +
There's no way to specify this through `argparse`?

2023-05-31 18:35 UTC, jtherrmann commented on src/hyp3_isce2/insar_tops_burst.py
> +
Just kidding, @AndrewPlayer3 found the right way to do it!

2023-05-31 18:45 UTC, jtherrmann commented on src/hyp3_isce2/insar_tops_burst.py
> +        secondary_scene: Secondary burst name
```suggestion
        secondary_scene: Secondary burst name
        swath_number: Number of swath to grab bursts from (1, 2, or 3) for IW
```

2023-05-31 18:46 UTC, jtherrmann commented on src/hyp3_isce2/insar_tops_burst.py
> +        secondary_scene: Secondary burst name
```suggestion
        secondary_scene: Secondary burst name
        swath_number: Number of swath to grab bursts from (1, 2, or 3) for IW
```

2023-05-31 18:52 UTC, jtherrmann approved these changes

2023-05-31 18:56 UTC, merged